version: '3'
services:
  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5050:5050'
    volumes:
      - .:/auth-service
    stdin_open: true
